### ISSUE TITLE
Receive arguments from the resolved Promise in condition

### ISSUE THREAD

**Issue by kevva** [sindresorhus/p-whilst#2]
When doing loops with HTTP requests, e.g. pagination, you need to check the response to decide whether to continue or not. Instead of defining a variable outside the Promise, it would be useful to receive the resolved value in the condition.

If you've left this out intentionally you can just forget about this issue :).

**Comment by SamVerschueren** [comment]
Seems like a valid use case to me.

**Comment by sindresorhus** [comment]
Yup, valid use-case. Just didn't think of it when doing this module.

**Comment by kevva** [comment]
How should we do with the first call then? Should we force the user to check if anything is resolved in the condition (see example below), or should the first one run regardless?

```js
pWhilst(res => {
    return res && res.next;
}, somePromise);
```

**Comment by SamVerschueren** [comment]
I think we should return undefined. We could also create a `pDoWhilst` or something :). Not sure though.

**Comment by sindresorhus** [comment]
> We could also create a `pDoWhilst` or something

https://github.com/sindresorhus/p-do-whilst
